### PR TITLE
TypeScript Declarations

### PR DESCRIPTION
**Pull request by knexator**
Hello again!
To use Shaku in TypeScript projects, I've found convenient to generate declaration files.
Generating them should be an automatic process by the typescript compiler, but it's not that smooth: some things don't get picked by it (such as the CSS color getters of Color), and other times there are bugs in the compiler (adding the _value property confuses it?? idk). I've made a python script to fix these things.

I've also fixed the typings for enum types: there used to be functions that expected as a param a "MouseButtons", for example, when "MouseButtons" is the enum itself instead of its values. I've fixed this, but note that for consistency I renamed "TextAlignment" to "TextAlignments", which breaks existing code (i've patched the repo examples)

There are still some weird issues (declarations seem to be duplicated or even triplicated; the declaration for createRenderTarget can't pick up that "name" is "String | null" instead of "String"; my fiddling in the python script seems to break the source maps) but overall it's pretty usable.

### CODE REVIEW

**Comment by knexator** [comment]
Huh, it seems that typescript projects don't work: either I do `import Vector2 from "shaku/lib/utils/vector2";`, in which case the type declarations don't work, or I do `import Vector2 from "shaku/types/utils/vector2";`, in which case it doesn't compile :(

I've read the relevant documentation from package.json, declaration publishing, searched for similar problems (https://stackoverflow.com/questions/72052916/how-to-import-js-module-when-typescript-declaration-file-is-located-in-a-separat). The only solution i've found is to place the .d.ts files all over /lib, but that's muddy and very unclear. Any solutions/suggestions welcome!

**Comment by knexator** [comment]
I've found a workaround: in typescript projects using Shaku, add
`"baseUrl": ".",
    "paths": {
      "shaku/lib/*": ["./node_modules/shaku/types/*"]
    }`
   to tsconfig.json, and import using `import Shaku from "shaku/lib/shaku";` `import Vector2 from "shaku/lib/utils/vector2"`

**Comment by RonenNess** [comment]
Hi @knexator thank you for the additional contribution!
I never used TypeScript so I'll have to trust your judgement on the proposed solution.

I'll check out the changes hopefully this weekend to see if they are acceptable and don't break too much. Will keep you updated.

Thanks :D

**Comment by RonenNess** [comment]
Can you explain more about why the enum def is without the S but the object containing the values is with S and not both the same? For example here:

```

/** @typedef {String} BlendMode */

/**
 * Blend modes we can draw with, determine how we blend new draws with existing buffer.
 * @readonly
 * @enum {BlendMode}
 */
const BlendModes = {
    AlphaBlend: "alpha",
    Opaque: "opaque",
    Additive: "additive",
    Multiply: "multiply",
    Subtract: "subtract",
    Screen: "screen",
    Overlay: "overlay",
    Invert: "invert",
    Darken: "darken",
    DestIn: "dest-in",
    DestOut: "dest-out"
};
```

Why did you make the comment / type called `BlendMode` and not `BlendModes` like the object itself?

Thanks

**Comment by knexator** [comment]
According to https://jsdoc.app/tags-enum.html, the `Type` in `@enum {Type}` is the type of the enum's values, not the type of the enum itself. So the type `BlendModes` is a constant object, whose values are of type `BlendMode` (which is actually just a string)

**Comment by RonenNess** [comment]
Ahh I understand now, first you defined a type, `BlendMode`, which is string. Then you made the enum *type* be value of BlendMode, aka string but in docs it will have a clearer name.

Sounds legit. I'll merge the pr branch soon, meanwhile feel free to go over my added commits if you got anything to add.

Thanks!

**Comment by RonenNess** [comment]
Merged, thanks @knexator! :)

**Pull request merged**
